name: Pull Request

# Run this workflow every time a commit gets pushed to main or a pull request gets opened against main
on:
  pull_request:
    branches: 
      - main

jobs:
    build:
        name: Pull Request Validation Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://msazure.visualstudio.com/DefaultCollection/OneAgile
            azure-pipeline-name: 'Power Fx-Dataverse-PullRequest'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
